// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kazune-br/go-orm-challange/internal/gateway/sqlboilerorm"
)

// Injectors from injector.go:

func InitRegistry() *sqlboilerorm.ComponentRegistry {
	rdbConnector := sqlboilerorm.NewMySQLConnector()
	iBoilerRepository := sqlboilerorm.NewBoilerRepository(rdbConnector)
	componentRegistry := sqlboilerorm.NewComponentRegistry(rdbConnector, iBoilerRepository)
	return componentRegistry
}
